name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3 # Specify your Ruby version
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Specify your Node.js version
        cache: 'npm' # enables caching of npm dependencies

    - name: Install npm dependencies
      run: npm ci

    - name: Build site for production
      run: npm run build:production

    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
       build_dir: _site/
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

